apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-ingress
  namespace: docker

spec:
  rules:
    - host: registry.brotherlogic-backend.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  docker
                port:
                  number: 5000

---

apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: docker
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
type: kubernetes.io/tls