apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-ingress
  namespace: docker
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls: 
   tls:
    - secretName: registry-brotherlogic-backend-com-tls
      hosts:
        - registry.brotherlogic-backend.com
  rules:
  - host: registry.brotherlogic-backend.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  docker
            port:
              number: 5000