apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-ingress
  namespace: docker

spec:
  tls: 
  - hosts:
      - registry.brotherlogic-backend.com
    secretName: tls-secret
  rules:
  - host: registry.brotherlogic-backend.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  docker
            port:
              number: 5000