apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-repo-pv
  namespace: docker
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: toru
    path: "/media/raid/kube/docker"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-repo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi